<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNMJP5KS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNMJP5KS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNMJP5KS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNMJP5KS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNMJP5KS\App_KernelDevDebugContainer([
    'container.build_hash' => 'NMJP5KS',
    'container.build_id' => '305aadcc',
    'container.build_time' => 1631799931,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNMJP5KS');
